#!/usr/bin/env bash
set -e

apt-get install -y \
    autoconf \
    patch \
    build-essential \
    rustc \
    libreadline6-dev \
    libncurses5-dev \
    libgdbm6 \
    libgdbm-dev \
    libdb-dev \
    uuid-dev
