#!/usr/bin/env bash
set -e

TOOL_NAME=$1
TOOL_DIR=$HOME/.asdf/toolset/$TOOL_NAME

# Install tool plugin
asdf plugin-add $TOOL_NAME $(< $TOOL_DIR/plugin-repo)

# Install tool dependencies
source $TOOL_DIR/build-env

# Install tool
asdf install ${TOOL_NAME} $(< $TOOL_DIR/version)

# Register tool installed version
echo "${TOOL_NAME} $(< $TOOL_DIR/version)" >> .tool-versions
